export const MIN_START_MS = 60 * 1000 // 1-minute per-player floor
export const DEFAULT_START_MS = 15 * 60 * 1000 // default per-player clock (about 30 min total for two players)
export const BASE_CHAKRA = 5 // game base chakra each player starts on
export const DEFAULT_ROUND_MS = 30 * 60 * 1000 // default shared round-timer duration
export const STORAGE_KEY = 'mythos-match-v1'
export const TICK_MS = 250 // render cadence for live timers
export const WARN_MS = 2 * 60 * 1000 // clock turns amber at/under 2 minutes
export const DANGER_MS = 30 * 1000 // clock turns red and pulses at/under 30 seconds
export const DELTA_WINDOW_MS = 3 * 1000 // quiet time before the live stat delta fades and a log entry stops merging
